# Generated by Django 3.2 on 2021-05-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_rename_patient_address_provider_provider_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_name',
        ),
    ]
