# Generated by Django 3.2 on 2021-05-13 04:10

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20210503_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerhistory',
            name='version',
            field=concurrency.fields.IntegerVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddField(
            model_name='patientpreferredtime',
            name='version',
            field=concurrency.fields.IntegerVersionField(default=0, help_text='record revision number'),
        ),
    ]
